# Generated by Django 4.2.27 on 2026-01-13 03:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cargo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('salario_base', models.DecimalField(decimal_places=2, help_text='Ingresa el salario en pesos', max_digits=10, verbose_name='Salario Base')),
                ('nivel_requerido', models.CharField(choices=[('junior', 'Junior'), ('semior', 'Semi-Senior'), ('senior', 'Senior'), ('lider', 'Líder')], default='junior', max_length=50, verbose_name='Nivel Requerido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Sucursal')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(default='Bogotá', max_length=100, verbose_name='Ciudad')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(help_text='Documento único de identificación', max_length=20, unique=True, verbose_name='Cédula/Documento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Teléfono inválido', regex='^\\+?[\\d\\s\\-\\(\\)]{7,}$')], verbose_name='Teléfono')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('foto', models.ImageField(blank=True, help_text='Foto de perfil del empleado (opcional)', null=True, upload_to='empleados/fotos/', verbose_name='Foto de Perfil')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('licencia', 'En Licencia'), ('despedido', 'Despedido')], default='activo', max_length=20, verbose_name='Estado')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='employees.cargo', verbose_name='Cargo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='employees.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['cedula'], name='employees_e_cedula_b3b6aa_idx'), models.Index(fields=['email'], name='employees_e_email_e53cb7_idx'), models.Index(fields=['estado'], name='employees_e_estado_af4575_idx')],
            },
        ),
    ]
