# Generated by Django 6.0.1 on 2026-01-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='minutos_atraso',
            field=models.PositiveIntegerField(default=0, verbose_name='Minutos de Atraso'),
        ),
    ]
