# Generated by Django 6.0.1 on 2026-01-23 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_registroasistencia_minutos_atraso'),
        ('core', '0001_initial'),
        ('employees', '0003_contrato_documentoempleado_kpi_puesto_resultadokpi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tipo', models.CharField(choices=[('checkin', 'Check-in'), ('checkout', 'Check-out')], max_length=10)),
                ('registrado_el', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.CharField(choices=[('web', 'Web'), ('app', 'App')], default='web', max_length=10)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('dentro_geocerca', models.BooleanField(default=False)),
                ('foto_evidence', models.ImageField(blank=True, null=True, upload_to='asistencia/fotos/')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asistencia', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Evento de Asistencia',
                'verbose_name_plural': 'Eventos de Asistencia',
                'ordering': ['-registrado_el'],
            },
        ),
        migrations.CreateModel(
            name='Geocerca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('circulo', 'Círculo'), ('poligono', 'Polígono')], max_length=20)),
                ('coordenadas', models.JSONField(help_text='Para círculo: {center:{lat,lng}, radius_m}. Para polígono: lista de puntos.')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geocercas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Geocerca',
                'verbose_name_plural': 'Geocercas',
            },
        ),
        migrations.CreateModel(
            name='ReglaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('considera_tardanza_min', models.PositiveIntegerField(default=5)),
                ('ip_permitidas', models.JSONField(blank=True, default=list)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_asistencia', to='core.empresa')),
                ('geocerca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas', to='attendance.geocerca')),
            ],
            options={
                'verbose_name': 'Regla de Asistencia',
                'verbose_name_plural': 'Reglas de Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(default='Turno General', max_length=120)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de días 0-6 (lunes-domingo)')),
                ('tolerancia_minutos', models.PositiveIntegerField(default=5)),
                ('requiere_gps', models.BooleanField(default=True)),
                ('requiere_foto', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='JornadaCalculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('minutos_trabajados', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('tardanza', 'Tardanza')], default='incompleto', max_length=15)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_calculadas', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Jornada Calculada',
                'verbose_name_plural': 'Jornadas Calculadas',
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
