# Generated by Django 6.0.1 on 2026-02-02 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_workshift'),
        ('employees', '0008_alter_contract_options_remove_contract_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('CHECK_IN', 'Check in'), ('CHECK_OUT', 'Check out'), ('LUNCH_START', 'Almuerzo inicio'), ('LUNCH_END', 'Almuerzo fin')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-timestamp'],
            },
        ),
    ]
