# Generated by Django 6.0.1 on 2026-01-24 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leaverequest_empleado'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leaves_leav_emplead_372f87_idx',
            old_name='leaves_leave_emplead_5605b1_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leaves_leav_start_d_96457d_idx',
            old_name='leaves_leave_start_d_c07e7d_idx',
        ),
    ]
