# Generated by Django 6.0.1 on 2026-01-23 04:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0002_empleado_reports_to_contract_leaverequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tipo', models.CharField(choices=[('indefinido', 'Indefinido'), ('plazo_fijo', 'Plazo Fijo'), ('pasantia', 'Pasantía'), ('obra_labor', 'Obra o Labor')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jornada_semanal_horas', models.PositiveIntegerField(default=40)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido')], default='activo', max_length=15)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('anexo', 'Anexo'), ('certificacion', 'Certificación'), ('otros', 'Otros')], max_length=30)),
                ('archivo', models.FileField(upload_to='empleados/documentos/')),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento de Empleado',
                'verbose_name_plural': 'Documentos de Empleado',
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(max_length=150)),
                ('formula', models.JSONField(blank=True, null=True)),
                ('unidad', models.CharField(default='%', max_length=20)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('junior', 'Junior'), ('semi', 'Semi Senior'), ('senior', 'Senior'), ('lider', 'Líder')], default='junior', max_length=20)),
                ('salario_referencial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('periodo', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cumplimiento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Resultado KPI',
                'verbose_name_plural': 'Resultados KPI',
            },
        ),
        migrations.CreateModel(
            name='SaldoVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('periodo', models.PositiveIntegerField(help_text='Año del periodo, ej. 2025')),
                ('dias_disponibles', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Saldo de Vacaciones',
                'verbose_name_plural': 'Saldos de Vacaciones',
            },
        ),
        migrations.CreateModel(
            name='SolicitudAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='ausencias/adjuntos/')),
            ],
            options={
                'verbose_name': 'Solicitud de Ausencia',
                'verbose_name_plural': 'Solicitudes de Ausencia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(max_length=100)),
                ('afecta_sueldo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Ausencia',
                'verbose_name_plural': 'Tipos de Ausencia',
            },
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='empleado',
            name='employees_e_cedula_b3b6aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='empleado',
            name='employees_e_email_e53cb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='empleado',
            name='employees_e_estado_af4575_idx',
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='documento',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto_url',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/fotos/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunidades', to='employees.sucursal'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='tipo',
            field=models.CharField(choices=[('sede', 'Sede'), ('area', 'Área')], default='sede', max_length=20),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='ubicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nivel_requerido',
            field=models.CharField(choices=[('junior', 'Junior'), ('semior', 'Semi-Senior'), ('senior', 'Senior'), ('lider', 'Líder')], default='junior', max_length=50),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_contracts', to='employees.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('licencia', 'En Licencia'), ('despedido', 'Despedido')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='employees.sucursal'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Teléfono inválido', regex='^\\+?[\\d\\s\\-\\(\\)]{7,}$')]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['empresa', 'nombre'], name='employees_s_empresa_18d02c_idx'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='documentoempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='employees.sucursal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='employees.puesto'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['empresa', 'documento'], name='employees_e_empresa_f1b4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['empresa', 'email'], name='employees_e_empresa_f2953f_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['empresa', 'estado'], name='employees_e_empresa_32b2b5_idx'),
        ),
        migrations.AddField(
            model_name='resultadokpi',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_kpi', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='resultadokpi',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='employees.kpi'),
        ),
        migrations.AddField(
            model_name='saldovacaciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_vacaciones', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudausencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_ausencia', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudausencia',
            name='tipo_ausencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='employees.tipoausencia'),
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='reports_to',
        ),
        migrations.AddIndex(
            model_name='puesto',
            index=models.Index(fields=['empresa', 'nombre'], name='employees_p_empresa_63c3c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadokpi',
            unique_together={('empleado', 'kpi', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='saldovacaciones',
            unique_together={('empleado', 'periodo')},
        ),
    ]
