# Generated by Django 6.0.1 on 2026-01-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0004_harden_required_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='puesto',
            name='employees_p_empresa_63c3c9_idx',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='puesto',
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nombre'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='nivel_requerido',
        ),
        migrations.AddField(
            model_name='cargo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='nivel',
            field=models.CharField(choices=[('junior', 'Junior'), ('semior', 'Semi-Senior'), ('senior', 'Senior'), ('lider', 'Líder')], default='junior', max_length=50),
        ),
        migrations.AddField(
            model_name='cargo',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='employees.sucursal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='employees.cargo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['empresa', 'nombre'], name='employees_c_empresa_1c58cb_idx'),
        ),
        migrations.DeleteModel(
            name='Puesto',
        ),
    ]
