# Generated by Django 6.0.1 on 2026-01-27 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_eventoasistencia_geocerca_reglaasistencia_turno_and_more'),
        ('employees', '0006_empleado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='beneficios',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.CharField(default='RRHH', max_length=80),
        ),
        migrations.AddField(
            model_name='cargo',
            name='responsabilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='salario_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cargo',
            name='salario_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contrato',
            name='beneficios',
            field=models.JSONField(blank=True, help_text='Beneficios adicionales, en JSON o lista', null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='attendance.turno'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salario mensual acordado', max_digits=12),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=0, help_text='Capacidad máxima de personal en la sucursal'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='direccion_exacta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='gerente_encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_a_cargo', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
