# Generated by Django 6.0.1 on 2026-01-28 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_workshift'),
        ('employees', '0007_cargo_beneficios_cargo_departamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date'], 'verbose_name': 'Contrato (nuevo)', 'verbose_name_plural': 'Contratos (nuevos)'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='document',
        ),
        migrations.AddField(
            model_name='contract',
            name='schedule_description',
            field=models.CharField(default='L-V 9-18', max_length=120),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='current_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='attendance.workshift'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('PLAZO_FIJO', 'Plazo Fijo'), ('SERVICIOS_PRO', 'Servicios Pro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='employees.empleado'),
        ),
    ]
