# Generated by Django 6.0.1 on 2026-01-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('ruc_nit', models.CharField(max_length=30, unique=True)),
                ('pais', models.CharField(choices=[('EC', 'Ecuador'), ('CO', 'Colombia'), ('PE', 'Perú'), ('MX', 'México'), ('CL', 'Chile'), ('AR', 'Argentina'), ('US', 'Estados Unidos'), ('ES', 'España')], default='EC', max_length=5)),
                ('moneda', models.CharField(choices=[('USD', 'Dólar'), ('EUR', 'Euro'), ('COP', 'Peso Colombiano'), ('PEN', 'Sol Peruano'), ('MXN', 'Peso Mexicano'), ('CLP', 'Peso Chileno'), ('ARS', 'Peso Argentino')], default='USD', max_length=5)),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
