# Generated by Django 6.0.1 on 2026-01-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='direccion_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('GERENTE_SUCURSAL', 'Gerente Sucursal'), ('RRHH', 'RRHH'), ('EMPLOYEE', 'Colaborador')], default='EMPLOYEE', max_length=20),
        ),
    ]
