# Generated by Django 6.0.1 on 2026-01-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_direccion_fiscal_empresa_representante_legal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo Corporativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='creada_el',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion_fiscal',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección Fiscal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo URL (Legacy)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar'), ('EUR', 'Euro'), ('COP', 'Peso Colombiano'), ('PEN', 'Sol Peruano'), ('MXN', 'Peso Mexicano'), ('CLP', 'Peso Chileno'), ('ARS', 'Peso Argentino')], default='USD', max_length=5, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Comercial'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(choices=[('EC', 'Ecuador'), ('CO', 'Colombia'), ('PE', 'Perú'), ('MX', 'México'), ('CL', 'Chile'), ('AR', 'Argentina'), ('US', 'Estados Unidos'), ('ES', 'España')], default='EC', max_length=5, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Representante Legal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='RUC/NIT/Tax ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc_nit',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='RUC/NIT (Legacy)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Debe Cambiar Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN_RRHH', 'Administrador RRHH'), ('MANAGER', 'Manager/Gerente'), ('EMPLOYEE', 'Empleado')], default='EMPLOYEE', max_length=20, verbose_name='Rol del Usuario'),
        ),
    ]
